---
title: "ER Analyses"
author: "JMH"
date: "9 Jan 2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo= FALSE}
library(tidyverse)
library(here)
library(mgcViz)
library(MuMIn)
library(mgcv)
library(forecast)
library(gridExtra)
library(tidymv)
library(ggpubr)
```

# Load & munge data
```{r}
load(file.path(here::here("04_SavedImages"), "02_ERanalyses_AMB_rdat"))
```


```{r message=FALSE, warning=FALSE}
met <- readr::read_csv(file = file.path(here::here("01_Data"),"01_MundgedMetabDat.csv")) %>% 
  mutate(stream = fct_relevel(stream, c("st11U", "st18", "st9", "st6")),
         treatment = fct_relevel(treatment, c("ambient", "nitrogen", "phosphorus")),
         Yf = as.factor(Yf),
         streamTreat = as.factor(streamTreat)) %>% 
  filter(treatment == "ambient") %>% 
  droplevels()

```



# ER Plots
Big differences among treatments. Normalish
```{r echo=FALSE}
ggplot(met, aes(y = lER, x = doy)) +
  geom_point()+
  stat_smooth() +
  facet_wrap(vars(stream))
```

```{ recho=FALSE}
ggplot(met, aes(y = meanQds, x = doy, color = treatment, shape = ppdoy180)) +
  geom_point()+
  stat_smooth() +
  facet_wrap(vars(stream))
```


```{r echo=FALSE}
ggplot(met, aes(sample = lER)) +stat_qq() + stat_qq_line() 
```


```{r echo=FALSE}
ggplot(met, aes(sample = lER, color = stream)) +stat_qq() + stat_qq_line() +
  facet_grid(.~stream)
```



```{r echo= FALSE}
BestERCor <- corARMA(p = 1,q = 1, form = ~ doy | streamTreat)
```


## Model sel
```{r echo=FALSE, include = T}
# g.modsel_t <- uGamm(lER ~ invKT.C.StMean  + s(LightPerDay.lcg),
#                 correlation = BestERCor, REML = FALSE, data = met,
#                 control = lmeControl(maxIter = 1e8, msMaxIter = 1e8, niterEM = 1000), class = "gamm")
# 
# g.modsel_s <- uGamm(lER ~ stream  + s(LightPerDay.lcg),
#                 correlation = BestERCor, REML = FALSE, data = met,
#                 control = lmeControl(maxIter = 1e8, msMaxIter = 1e8, niterEM = 1000), class = "gamm")
# 
# 
# g.Dredge_t <-  dredge(global.model = g.modsel_t, evaluate = TRUE, rank = AICc)
# g.Dredge_s <-  dredge(global.model = g.modsel_s, evaluate = TRUE, rank = AICc)

```



```{r echo=FALSE}
g.DredgeSumF <- merge(g.Dredge_t, g.Dredge_s)
```

### Model selection 

#### all models
```{r echo=FALSE}
subset(g.DredgeSumF, delta <= 2)
```

```{r}
write_csv(g.DredgeSumF,
          file.path(here::here("06_AICtables"), "02d_ER_AMB.csv"))
```



```{r}
g.er.BEST <- gamm(lER ~ invKT.C.StMean + s(LightPerDay.lcg),
                correlation = BestERCor, REML = TRUE, data = met,
                control = lmeControl(maxIter = 1e8, msMaxIter = 1e8, niterEM = 1000))
```

```{r}
g.er.BEST_s <- gamm(lER ~ stream + s(LightPerDay.lcg),
                correlation = BestERCor, REML = TRUE, data = met,
                control = lmeControl(maxIter = 1e8, msMaxIter = 1e8, niterEM = 1000))
```



### Best models
#### Overall

```{r}
summary(g.er.BEST$gam)
```

```{r}
plot(g.er.BEST$gam)
```


Looks good
```{r}
round(concurvity(g.er.BEST$gam, full = FALSE)$estimate,3)
```

```{r}
g.er.BEST.gv <- getViz(g.er.BEST$gam)
```

```{r}
check(g.er.BEST.gv)
```

One last check on the autocorrelation. Little issue with S18
```{r echo= FALSE}
g.er.best.acf <- met %>% 
  mutate(g.erRes = resid(g.er.BEST$lme, type = "normalized")) %>% 
  select(streamTreat, g.erRes) %>% 
  group_by(streamTreat) %>% 
  nest() %>% 
  mutate(acf = map(.x = data, .f = function(d) ggAcf(d$g.erRes) + labs(title = streamTreat)))
```

```{r echo= FALSE}
grid.arrange(grobs = g.er.best.acf$acf, ncol = 3)
```

```{r echo=FALSE}
metBestTest <- met %>% 
  mutate(erres1 = residuals(g.er.BEST$gam, type = "response"),
         erPred1 = predict(g.er.BEST$gam, type = "response"))
```


 Check residuals

```{r echo=FALSE}
ggplot(metBestTest, aes(y = erres1, x = DOYres2, color = stream, shape = treatment)) +
  geom_point() +
  facet_grid(stream ~ treatment) 
```

```{r echo=FALSE}
ggplot(metBestTest, aes(y = lER, x = erPred1, color = stream, shape = treatment)) +
  geom_point() +
  geom_abline(intercept = 0, slope = 1)
```

```{r}
summary(g.er.BEST_s$gam)
```


### save results
```{r echo = FALSE, include = FALSE}
# saveRDS(g.er.BEST,
#         file = file.path(here::here("05_SavedModels"), "02d_ER_AMB_Best.rds"))
# saveRDS(g.er.BEST_s,
#         file = file.path(here::here("05_SavedModels"), "02d_ER_AMB_stream.rds"))

```


```{r echo = FALSE, include = FALSE}
# save.image(file.path(here::here("04_SavedImages"), "02_ERanalyses_AMB_rdat"))
```












